services:
  # Hamma-xizmat-birda (Web Service)
  - type: web
    name: avtosavdo-bot
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: avtosavdo-db
          property: connectionString
      # Redis endi ichkarida (localhost)
      - key: REDIS_URL
        value: redis://localhost:6379/0
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379/0
      - key: CELERY_Result_BACKEND
        value: redis://localhost:6379/0
      - key: PORT
        value: 10000

# Bepul Baza (90 kundan keyin yangilash kerak, yoki $7 to'lash kerak)
databases:
  - name: avtosavdo-db
    plan: free
    databaseName: avtosavdo
    user: avtosavdo_user
