services:
  # Hamma-xizmat-birda (Web Service)
  - type: web
    name: avtosavdo-bot
    env: docker
    plan: free
    region: frankfurt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: PORT
        value: 10000

# Bepul Baza (90 kundan keyin yangilash kerak, yoki $7 to'lash kerak)
databases:
  - name: avtosavdo-db
    plan: free
    databaseName: avtosavdo
    user: avtosavdo_user
